Anoosha-GenEpio-01
GenEpiO/genepio pull request #47
Opened 2022-09-23 18:57 UTC by Anoosha-Sehar

GRDI Dexa terms curated by Emma and Anoosha

2022-11-22 23:23 UTC, cmrn-rhi approved these changes

2022-11-22 23:24 UTC, cmrn-rhi commented
@ddooley alright with you if we merge this?

2022-11-22 23:34 UTC, ddooley requested changes

2022-11-23 04:01 UTC, Anoosha-Sehar commented on src/ontology/genepio-edit.owl
> +AnnotationAssertion(dc11:contributor obo:GENEPIO_0002122 "A sterilized sampling bag that is puncture proof tabs for protection from damage due to wire-end protrusion and leak-proof closures."@en)
Oh yes, my mistake. Thanks for pointing that out. I just fixed it.

2022-11-23 04:46 UTC, ddooley commented on src/ontology/genepio-edit.owl
> +AnnotationAssertion(dc11:contributor obo:GENEPIO_0002122 "A sterilized sampling bag that is puncture proof tabs for protection from damage due to wire-end protrusion and leak-proof closures."@en)
Ok, but it wasn't just that 'clinical trial sampling strategy'] item I was talking about. There are others sampling strategies that need longer labels too.

2022-11-23 05:45 UTC, Anoosha-Sehar commented on src/ontology/genepio-edit.owl
> +AnnotationAssertion(dc11:contributor obo:GENEPIO_0002122 "A sterilized sampling bag that is puncture proof tabs for protection from damage due to wire-end protrusion and leak-proof closures."@en)
Hmm right. I thought these strategies are usually recognized by these names, like survey study strategy. But maybe it's a better idea to explicitly name them as 'sampling strategy' so to bring more clarity.

2022-11-23 06:50 UTC, ddooley commented on src/ontology/genepio-edit.owl
> +AnnotationAssertion(dc11:contributor obo:GENEPIO_0002122 "A sterilized sampling bag that is puncture proof tabs for protection from damage due to wire-end protrusion and leak-proof closures."@en)
For me the issue is when these terms show up in a search engine and we want to guide people away from making the wrong choice.  The label "field experiment" is a different concept from a "field experiment sampling strategy".

2022-11-23 19:25 UTC, Anoosha-Sehar commented on src/ontology/genepio-edit.owl
> +AnnotationAssertion(dc11:contributor obo:GENEPIO_0002122 "A sterilized sampling bag that is puncture proof tabs for protection from damage due to wire-end protrusion and leak-proof closures."@en)
I agree, and that completely makes sense. Thank you. 
I've updated the labels accordingly. Please let me know if there is any other thing which should be updated.

2022-11-24 00:01 UTC, ddooley approved these changes

2022-11-24 00:04 UTC, merged